apiVersion: v1
kind: Template
labels:
  template: air-traffic-control-build
metadata:
  annotations:
    description: Build the Air Traffic Control Image
    iconClass: icon-python
    tags: python
  name: air-traffic-control-build
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:latest
    source:
      contextDir: ${CONTEXT_DIR}
      git:
        ref: ${SOURCE_REPOSITORY_REF}
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: ${BASE_IMAGESTREAMTAG}
          namespace: ${BASE_IMAGESTREAM_NAMESPACE}
      type: Source
    triggers:
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
  value: air-traffic-control
- description: Git source URI for application
  name: SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/elmiko/late-departures
- description: Git branch/tag reference
  name: SOURCE_REPOSITORY_REF
  required: false
  value: master
- description: Path within Git project to build; empty for root project directory.
  name: CONTEXT_DIR
  required: false
  value: air-traffic-control
- description: Base ImageStream Tag
  name: BASE_IMAGESTREAMTAG
  required: true
  value: python-36-centos7:latest
- description: Base ImageStream Namespace
  name: BASE_IMAGESTREAM_NAMESPACE
  required: false