apiVersion: v1
kind: Template
labels:
  template: flight-listener-build
metadata:
  annotations:
    description: Build the Flight Listener Image
    iconClass: icon-python
    tags: python
  name: flight-listener-build
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:latest
    source:
      contextDir: ${CONTEXT_DIR}
      git:
        ref: ${SOURCE_REPOSITORY_REF}
        uri: ${SOURCE_REPOSITORY_URL}
      type: Git
    strategy:
      sourceStrategy:
        env:
          - name: APP_FILE
            value: ${APP_FILE}
        forcePull: true
        from:
          kind: DockerImage
          name: ${SOURCE_IMAGE}  
      type: Source
    triggers:
    - imageChange: {}
      type: ImageChange
    - type: ConfigChange
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
  value: flight-listener
- description: Git source URI for application
  name: SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/elmiko/late-departures
- description: Git branch/tag reference
  name: SOURCE_REPOSITORY_REF
  required: false
  value: master
- description: Path within Git project to build; empty for root project directory.
  name: CONTEXT_DIR
  required: false
  value: flight-listener
- description: Source Image
  name: SOURCE_IMAGE
  required: true
  value: radanalyticsio/radanalytics-pyspark:stable
- description: The name of the main py file to run. If this is not specified and there
    is a single py file at top level of the git respository, that file will be chosen.
  name: APP_FILE
